### ISSUE TITLE
Sometimes when loading a publisher page it shows no data on first load

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/qualitydashboard#8]
There looks to be a timing issue that means that sometimes the data doesn't display correctly on first load.  

https://qualitydashboard.threesixtygiving.org/publisher/360G-tnlcomfund

**Comment by mariongalley** [comment]
Is this still an issue? I haven't come across it

**Comment by mariongalley** [comment]
Nor I, happy to close
